# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: aquasecScanner@4
      inputs:
        image: 'centos:latest'
        scanType: 'hosted'
        register: false
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '4.2.0'
        scanner: 'registry.aquasec.com/scanner:6.5'
        registry: 'hub.docker.com'
        connection: 'aquascanner'
