# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-vdhar'
        command: 'start'
        arguments: '--image centos:latest --server https://df000251f1.cloud.aquasec.com/ --user --password *** --scanner registry.aquasec.com/scanner:6.5 --file-prefix AquaSecurity --scan-type local --registry --register true'
    