# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: AquaRegistryDockerLogin@2
        inputs:
          containerRegistry: 'aquascanner'
          command: 'login'
      - task: aquasecScanner@4
        inputs:
          image: 'nginx:latest'
          scanType: 'local'
          register: false
          hideBase: false
          showNegligible: false
          windowsScannerVersion: '4.2.0'
          scanner: 'registry.aquasec.com/scanner:6.5'
          registry: 'localhost'
          connection: 'aquaconsole'